export { defaultBrand as site } from "@/lib/brand";
import { exampleIntroVideoUrl, parseIntroVideo } from "@/lib/intro-video";

export const publicNav = [
  { href: "/teachers", label: "Find teachers", messageKey: "nav.find_teachers" },
  { href: "/subjects", label: "Subjects", messageKey: "nav.subjects" },
  { href: "/courses", label: "Courses", messageKey: "nav.courses" },
  { href: "/live-courses", label: "Live courses", messageKey: "nav.live_courses" },
  { href: "/group-lessons", label: "Group lessons", messageKey: "nav.group_lessons" },
  { href: "/parents", label: "For parents", messageKey: "nav.for_parents" },
  { href: "/teach", label: "Teach with us", messageKey: "nav.teach" },
] as const;

export const subjects = [
  {
    slug: "quran",
    name: "Qur'an",
    summary: "Recitation, fluency, and love of the Book — at the child's pace.",
    tone: "mint",
  },
  {
    slug: "tajweed",
    name: "Tajweed",
    summary: "Clear rules, gentle correction, and confident pronunciation.",
    tone: "gold",
  },
  {
    slug: "hifdh",
    name: "Hifdh",
    summary: "Memorisation and revision with a visual progress path.",
    tone: "peach",
  },
  {
    slug: "arabic",
    name: "Arabic",
    summary: "Reading, speaking, and grammar for children and adults.",
    tone: "sky",
  },
  {
    slug: "islamic-studies",
    name: "Islamic Studies",
    summary: "Age-appropriate aqidah, seerah, adab, and daily practice.",
    tone: "rose",
  },
] as const;

export const sampleTeachers = [
  {
    name: "Ustadha Amina Rahman",
    subjects: "Qur'an · Tajweed",
    subjectSlugs: ["quran", "tajweed"],
    languages: "English, Arabic",
    rating: "4.9",
    lessons: "320+",
    lessonsTaught: 320,
    reviewCount: 42,
    responseRate: 97,
    recommendPercent: 98,
    level: "Children & teens",
    gender: "female",
    audiences: ["children", "teens"],
    country: "GB",
    hasVideo: true,
    photoUrl: "/teachers/sample-1.svg",
    video: {
      watchUrl: exampleIntroVideoUrl,
      playback: parseIntroVideo(exampleIntroVideoUrl),
    },
    rate: {
      amountMinor: 1800,
      amount: "18.00",
      currencyCode: "GBP",
      formatted: "£18.00 / hour",
      studentPays: "£18.00",
    },
  },
  {
    name: "Ustadh Yusuf Haleem",
    subjects: "Hifdh · Qur'an",
    subjectSlugs: ["hifdh", "quran"],
    languages: "English, Urdu",
    rating: "4.8",
    lessons: "210+",
    lessonsTaught: 210,
    reviewCount: 28,
    responseRate: 91,
    recommendPercent: 95,
    level: "Beginner to hifdh",
    gender: "male",
    audiences: ["children", "teens"],
    country: "PK",
    hasVideo: true,
    photoUrl: "/teachers/sample-2.svg",
    video: {
      watchUrl: exampleIntroVideoUrl,
      playback: parseIntroVideo(exampleIntroVideoUrl),
    },
    rate: {
      amountMinor: 1600,
      amount: "16.00",
      currencyCode: "GBP",
      formatted: "£16.00 / hour",
      studentPays: "£16.00",
    },
  },
  {
    name: "Ustadha Layla Osman",
    subjects: "Arabic · Islamic Studies",
    subjectSlugs: ["arabic", "islamic-studies"],
    languages: "English, Arabic",
    rating: "5.0",
    lessons: "140+",
    lessonsTaught: 140,
    reviewCount: 16,
    responseRate: 88,
    recommendPercent: 94,
    level: "Families & adults",
    gender: "female",
    audiences: ["families", "adults"],
    country: "GB",
    hasVideo: true,
    photoUrl: "/teachers/sample-3.svg",
    video: {
      watchUrl: exampleIntroVideoUrl,
      playback: parseIntroVideo(exampleIntroVideoUrl),
    },
    rate: {
      amountMinor: 2000,
      amount: "20.00",
      currencyCode: "GBP",
      formatted: "£20.00 / hour",
      studentPays: "£20.00",
    },
  },
];
