export const facultyOrder = [
  "ios",
  "android",
  "login",
  "search",
  "booking",
  "payments",
  "classroom",
  "messaging",
  "homework",
  "reports",
  "progress",
  "notifications",
  "recordings",
  "materials",
  "push",
] as const;

export type FacultyId = (typeof facultyOrder)[number];

const en = {
  brand: "Al Haramain Schools",
  signIn: "Sign in",
  email: "Email",
  password: "Password",
  code: "Authenticator code",
  confirm: "Confirm",
  signOut: "Sign out",
  back: "Back",
  search: "Search teachers",
  book: "Book a lesson",
  student: "Student",
  starts: "Start time, such as 2026-09-29T15:00:00Z",
  send: "Send",
  reply: "Reply",
  register: "Register this device",
  pushOff: "Push delivery is not connected. Nothing is sent.",
  store: "Not submitted to the store.",
  webOnly: "Open this project in the iOS or Android app. The website is separate.",
  empty: "Nothing to show yet.",
  loading: "Loading",
  ios: "Dedicated iOS application",
  android: "Dedicated Android application",
  login: "Mobile login",
  searchTitle: "Teacher search",
  booking: "Booking",
  payments: "Payments",
  classroom: "Virtual classroom",
  messaging: "Messaging",
  homework: "Homework",
  reports: "Reports",
  progress: "Student progress",
  notifications: "Notifications",
  recordings: "Recordings",
  materials: "Learning materials",
  push: "Mobile and web push notifications",
  join: "Join classroom",
};

const ar: typeof en = {
  brand: "مدارس الحرمين",
  signIn: "تسجيل الدخول",
  email: "البريد",
  password: "كلمة المرور",
  code: "رمز المصادقة",
  confirm: "تأكيد",
  signOut: "تسجيل الخروج",
  back: "رجوع",
  search: "ابحث عن المعلمين",
  book: "احجز درساً",
  student: "الطالب",
  starts: "وقت البدء، مثل 2026-09-29T15:00:00Z",
  send: "إرسال",
  reply: "رد",
  register: "سجّل هذا الجهاز",
  pushOff: "تسليم الدفع غير متصل. لا يُرسل شيء.",
  store: "لم يُرسل إلى المتجر.",
  webOnly: "افتح هذا المشروع في تطبيق iOS أو Android. الموقع منفصل.",
  empty: "لا يوجد شيء بعد.",
  loading: "جارٍ التحميل",
  ios: "تطبيق iOS مستقل",
  android: "تطبيق Android مستقل",
  login: "دخول الجوال",
  searchTitle: "البحث عن معلم",
  booking: "الحجز",
  payments: "المدفوعات",
  classroom: "الصف الافتراضي",
  messaging: "الرسائل",
  homework: "الواجب",
  reports: "التقارير",
  progress: "تقدم الطالب",
  notifications: "الإشعارات",
  recordings: "التسجيلات",
  materials: "مواد التعلم",
  push: "إشعارات الدفع للجوال والويب",
  join: "انضم إلى الصف",
};

export function copy() {
  const locale = Intl.DateTimeFormat().resolvedOptions().locale || "en";
  return locale.toLowerCase().startsWith("ar") ? ar : en;
}

export function facultyTitle(id: FacultyId) {
  const text = copy();
  const titles: Record<FacultyId, string> = {
    ios: text.ios,
    android: text.android,
    login: text.login,
    search: text.searchTitle,
    booking: text.booking,
    payments: text.payments,
    classroom: text.classroom,
    messaging: text.messaging,
    homework: text.homework,
    reports: text.reports,
    progress: text.progress,
    notifications: text.notifications,
    recordings: text.recordings,
    materials: text.materials,
    push: text.push,
  };
  return titles[id];
}
